spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
  servlet:
    context-path: /client
client:
  request:
    logging: false
